# Generated by Django 4.1 on 2023-06-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_venue_email_alter_venue_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='phone',
            field=models.CharField(blank=True, max_length=120, verbose_name='Contact Phone'),
        ),
    ]
